Fix reading datasets from base_list if defined without '/' in the names.
Fix reading datasets from base_list if defined without '/' in the names
by using os.path.basename instead of trying to get the basename ourself
in a hacky way.

Fixes the following error when filenames listed  in datalist don't
contain slashes:

  File "./NGSCheckMate/ncm.py", line 254, in createDataSetFromList
    file = link[link.rindex("/")+1:]
ValueError: substring not found